### ISSUE TITLE
Allow field mapping in nested properties

### ISSUE THREAD

**Issue by fjuniorr** [fjuniorr/flowmapper#12]
The current [field mapping](https://github.com/fjuniorr/flowmapper-ci/blob/main/config/SimaProv9.4-ecoinventEFv3.7.toml) between names of source and target flows fields is:

```toml
[fields]

uuid = ["Flow UUID", "FlowUUID"]
name = ["Flowable"]
context = ["Context"]
unit = ["Unit"]
cas = ["CAS No", "CASNo"]
```

However some flow lists have nested properties in the `context` field, such as 

```json
  {
    "name": "Chrysotile",
    "context": [
      "Resources",
      "in ground"
    ],
    "unit": "kg"
  }
```

which we can't express with the current syntax. We probably want something like:

```toml
[fields]
name = ["name", "Flowable"]
context = [["context[0]", "context[1]"], "Context"]
unit = ["unit", "Unit"]
```

and integrate this with https://github.com/fjuniorr/flowmapper/issues/9

**Comment by cmutel** [comment]
I am really uncomfortable with the assumption that `Context` has exactly length two - could we please try to make this flexible?

**Comment by fjuniorr** [comment]
For sure @cmutel! 

My idea is to allow the use of something like a [JSONPath](https://goessner.net/articles/JsonPath/) notation so that we can map for example this input data:

```python
{
    "@casNumber": "7440-66-6",
    "@formula": "Zn",
    "@id": "be73218b-18af-492e-96e6-addd309d1e32",
    "@unitId": "487df68b-4994-4027-8fdc-a4dc298257b7",
    "compartment": {
        "@subcompartmentId": "6a098164-9f04-4f65-8104-ffab7f2677f3",
        "compartment": {"#text": "natural resource", "@xml:lang": "en"},
        "subcompartment": {"#text": "in ground", "@xml:lang": "en"},
    },
    "name": {"#text": "Zinc, in ground", "@xml:lang": "en"},
    "productInformation": None,
    "unitName": {"#text": "kg", "@xml:lang": "en"},
}
```  

with this field mapping:

```toml
[fields]
name = ["name", "Flowable"]
context = [["compartment.compartment.#text", "compartment.subcompartment.#text"], "Context"]
```

Do you know already if we might also need some sort of format string to allow a different concatenation strategy then simply `f"{context}, {subcontext}"`?
